version: '3.8'

services:
  app:
    image: askaurora_app:latest
    ports:
      - "8000:8000"
    environment:
      - RAW_DATA_DIR=data/raw_data
      - API_URL=https://november7-730026606190.europe-west1.run.app/messages
      - PAGE_LIMIT=500
      - MODEL=gpt-oss:20b-cloud
      - OLLAMA_API_KEY=<insert_your_key_here>
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
